Dropping support for python 2.7 and 3.5 (#5)
* drop support py2.7 and 3.5

* switched os -> pathlib

* don't check md5sum because the images are different -> compare them by L1 difference

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,21 +9,15 @@ addons:
 
 matrix:
   include:
-    - name: "conda 2.7"
-      python: 2.7
-      env: DISTRIB="conda"
 
-    - name: "pip 2.7"
-      python: 2.7
-      env: DISTRIB="pip"
-
-    - name: "pip 3.5"
-      python: 3.5
+    - name: "pip 3.6"
+      python: 3.6
       env: DISTRIB="pip"
 
     - name: "conda 3.7"
       python: 3.7
       env: DISTRIB="conda"
+      after_success: coveralls || echo "coveralls failed"
 
     - name: "conda 3.8"
       python: 3.8
@@ -35,19 +29,15 @@ matrix:
 
 install:
   - if [[ "${DISTRIB}" == "conda" ]];
-    # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
     then
-      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
-        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
-      else
-        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
-      fi
-      bash miniconda.sh -b -p $HOME/miniconda
-      source "$HOME/miniconda/etc/profile.d/conda.sh"
+      py_major=${TRAVIS_PYTHON_VERSION:0:1};
+      wget https://repo.continuum.io/miniconda/Miniconda${py_major}-latest-Linux-x86_64.sh -O miniconda.sh;
+      bash miniconda.sh -b -p $HOME/miniconda;
+      source "$HOME/miniconda/etc/profile.d/conda.sh";
       conda config --set always_yes yes;
       conda update conda;
-      conda info -a;
       conda env create -f requirements/environment.yml;
+      conda activate elephant;
       pip list;
     else
       pip install -r requirements/requirements.txt;
@@ -61,5 +51,3 @@ install:
 
 script:
   nosetests --with-coverage --cover-package=viziphant
-
-after_success: coveralls || echo "coveralls failed"
